Métodos numéricos

Estudiante: Bryan Morales

In [1]:
import numpy as np
from src import gauss_jacobi, gauss_seidel

[07-31 17:22:33][INFO] 2024-07-31 17:22:33.202036


1. Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por medio de $x^{(0)} = 0$

a. $3x_1 - x_2 + x_3 = 1$,

$3x_1+6x_2+2x_3 =0$,

$3x_1+3x_2+7x_3 = 4$

In [17]:
A1 =np.array( [
    [3,-1,1],
    [3,6,2],
    [3,3,7.]
])

B1 = np.array(
    [
        [1],
        [0],
        [4.]
    ]
)

print(gauss_jacobi(A=A1, b=B1, error=1e-3, max_iter=100))

(array([[ 0.03509079],
       [-0.23680635],
       [ 0.65793476]]), 11)


b. $10x_1 - x_2 = 9$,

$-x_1+10x_2-2x_3 =7$,

$-2x_2+10x_3 = 6$

In [18]:
A2 = np.array(
    [
        [10,-1,0],
        [-1,10,-2],
        [-2,0,10]
    ]
)
B2 = np.array(
    [
        [9],
        [7],
        [6]
    ]
)
print(gauss_jacobi(A=A2, b=B2, error=1e-3, max_iter=100))

(array([[0.995917],
       [0.959391],
       [0.799158]]), 6)


c. $10x_1 +5 x_2  = 6$,

$5x_1+10x_2-4x_3 =25$,

$-4x_2+8x_3-x_4 = -11$,

$-x_3+5x_4 = -11$

In [19]:
A3 = np.array(
    [
        [10,5,0,0],
        [5,10,-4,0],
        [0,-4,8,-1],
        [0,0,-1,5]
    ]
)
B3 = np.array(
    [
        [6],
        [25],
        [-11],
        [-11]
    ]
)
print(gauss_jacobi(A=A3, b=B3, error=1e-3, max_iter=100))

(array([[-0.79759387],
       [ 2.79528199],
       [-0.25887976],
       [-2.25176749]]), 27)


4. $4x_1 + x_2 + x_3 + x_5  = 6$,

$-x_1-3x_2+x_3+x_4 =6$,

$2x_1+x_2+5x_3-x_4-x_5 = 6$,

$-x_1-x_2-x_3+4x_4 = 6$,

$2x_2-x_3+x_4+4x_5 = 6$

In [20]:
A4 = np.array(
    [
        [4,1,1,0,1],
        [-1,-3,1,1,0],
        [2,1,5,-1,-1],
        [-1,-1,-1,4,0],
        [0,2,-1,1,4]
    ]
)
B4 = np.array(
    [
        [6],
        [6],
        [6],
        [6],
        [6]
    ]
)
print(gauss_jacobi(A=A4, b=B4, error=1e-3, max_iter=100))

(array([[ 0.78669256],
       [-1.00271775],
       [ 1.8663196 ],
       [ 1.9125416 ],
       [ 1.98984447]]), 14)


2. Ahora usando Gaus - Seidel

1. 

In [21]:
print(gauss_seidel(A=A1, b=B1, error=1e-3, max_iter=100))

(array([ 0.03508772, -0.23684211,  0.65789474]), 100)


2.

In [22]:
print(gauss_seidel(A=A2, b=B2, error=1e-3, max_iter=100))

(array([0.9959432 , 0.95943205, 0.79918864]), 100)


3.

In [23]:
print(gauss_seidel(A=A3, b=B3, error=1e-3, max_iter=100))

(array([-0.79764706,  2.79529412, -0.25882353, -2.25176471]), 100)


4.

In [50]:
print(gauss_seidel(A=A4, b=B4, error=1e-3, max_iter=100))

(array([ 0.78668253, -1.00271872,  1.86628339,  1.9125618 ,  1.98978976]), 7)


3. Usando el método de Jacobi para resolver el ejercicio 1 con una TOL = 1e-3

4. Usando el método de Gauss-Siedel para resolver el ejercicio 1 con una TOL = 1e-3

Notese que cada una de las implementaciones anteriores se resolvienron solicitando la TOL = 1e-3

5. El sistema lineal

$2x_1-x_2+x_3 = -1$,

$2x_1+2x_2+2x_3 = 4$,

$-x_1-x_2+2x_3 = -5$

tiene la solución (1,2,-1)

a. Muestre que el método de Jacobi con $x_{(0)}=0$ falla al proporcionar una buena aproximación despues de 25 iteraciones

In [3]:
A5 = np.array(
    [
        [2,-1,1],
        [2,2,2],
        [-1,-1,2]
    ]
)
B5 = np.array(
    [
        [-1],
        [4],
        [-5]
    ]
)
print(gauss_jacobi(A=A5, b=B5, max_iter=25, error=1e-7))



[07-31 17:23:49][INFO] 
[[4.5]
 [6. ]
 [1.5]]
[07-31 17:23:49][INFO] 
[[ 2.25]
 [-6.  ]
 [ 5.25]]
[07-31 17:23:49][INFO] 
[[-5.625]
 [-7.5  ]
 [-1.875]]
[07-31 17:23:49][INFO] 
[[-2.8125]
 [ 7.5   ]
 [-6.5625]]
[07-31 17:23:49][INFO] 
[[7.03125]
 [9.375  ]
 [2.34375]]
[07-31 17:23:49][INFO] 
[[ 3.515625]
 [-9.375   ]
 [ 8.203125]]
[07-31 17:23:49][INFO] 
[[ -8.7890625]
 [-11.71875  ]
 [ -2.9296875]]
[07-31 17:23:49][INFO] 
[[ -4.39453125]
 [ 11.71875   ]
 [-10.25390625]]
[07-31 17:23:49][INFO] 
[[10.98632812]
 [14.6484375 ]
 [ 3.66210938]]
[07-31 17:23:49][INFO] 
[[  5.49316406]
 [-14.6484375 ]
 [ 12.81738281]]
[07-31 17:23:49][INFO] 
[[-13.73291016]
 [-18.31054688]
 [ -4.57763672]]
[07-31 17:23:49][INFO] 
[[ -6.86645508]
 [ 18.31054688]
 [-16.02172852]]
[07-31 17:23:49][INFO] 
[[17.1661377 ]
 [22.88818359]
 [ 5.7220459 ]]
[07-31 17:23:49][INFO] 
[[  8.58306885]
 [-22.88818359]
 [ 20.02716064]]
[07-31 17:23:49][INFO] 
[[-21.45767212]
 [-28.61022949]
 [ -7.15255737]]
[07-31 17:23:49][IN

b. Utilice el método de GaussSiedel con $x_{(0)}=0$ para aproximar la solución para el sistema lineal dentro de $10^{-5}$

In [6]:
print(gauss_seidel(A=A5, b=B5, max_iter=100, error=1e-5))

[[ 4. -2.  4.]
 [ 9.  3.  9.]
 [ 0. -6.  0.]] [-0.5  2.5 -1.5]
[07-31 17:24:41][INFO] 
[[ 4. -2.  4.]
 [ 9.  3.  9.]
 [ 0. -6.  0.]]
[[ -1.25  -6.5    4.  ]
 [  3.75  -1.5    9.  ]
 [ -5.25 -10.5    0.  ]] [ 1.5   2.   -0.75]
[07-31 17:24:41][INFO] 
[[ -1.25  -6.5    4.  ]
 [  3.75  -1.5    9.  ]
 [ -5.25 -10.5    0.  ]]
[[ 0.25 -4.25  4.  ]
 [ 5.25  0.75  9.  ]
 [-3.75 -8.25  0.  ]] [ 0.875  1.875 -1.125]
[07-31 17:24:41][INFO] 
[[ 0.25 -4.25  4.  ]
 [ 5.25  0.75  9.  ]
 [-3.75 -8.25  0.  ]]
[[ 0.0625 -5.375   4.    ]
 [ 5.0625 -0.375   9.    ]
 [-3.9375 -9.375   0.    ]] [ 1.      2.125  -0.9375]
[07-31 17:24:41][INFO] 
[[ 0.0625 -5.375   4.    ]
 [ 5.0625 -0.375   9.    ]
 [-3.9375 -9.375   0.    ]]
[[-0.125  -4.8125  4.    ]
 [ 4.875   0.1875  9.    ]
 [-4.125  -8.8125  0.    ]] [ 1.03125  1.90625 -1.03125]
[07-31 17:24:41][INFO] 
[[-0.125  -4.8125  4.    ]
 [ 4.875   0.1875  9.    ]
 [-4.125  -8.8125  0.    ]]
[[ 0.109375 -5.09375   4.      ]
 [ 5.109375 -0.09375   9.      ]
 [-3.

6. El sistema lineal

$x_1 - x_3 = 0.2$,

$-\frac{1}{2}x_1+x_2-\frac{1}{4}x_3=-1.425$

$x_1 - \frac{1}{2}x_2+x_3 = 2$

hola
